### ISSUE TITLE
Because chewie >=1.2.0 depends on provider ^5.0.0

### ISSUE THREAD

**Issue by VNAPNIC** [fluttercommunity/chewie#580]
Because chewie >=1.2.0 depends on provider ^5.0.0 and flutter_bloc >=7.2.0 depends on provider ^6.0.0, chewie >=1.2.0 is incompatible with flutter_bloc >=7.2.0.
So, because baseflutter depends on both flutter_bloc ^7.3.0 and chewie ^1.2.2, version solving failed.
pub get failed (1; So, because baseflutter depends on both flutter_bloc ^7.3.0 and chewie ^1.2.2, version solving failed.)

**Comment by rahul-2501** [comment]
got the same issue

**Comment by mcagrigoktas** [comment]
+1

**Comment by OmarMahmoud120** [comment]
+1

**Comment by CalHoll** [comment]
+1

**Comment by mtrfnvwork** [comment]
+1

**Comment by matecode** [comment]
+1

**Comment by yunusemrecetin** [comment]
+1

**Comment by mshadmnaeo** [comment]
+1

**Comment by mirrorlink** [comment]
Same issue here. We need a 1.2.3 release with provider 6.0.0

**Comment by mirrorlink** [comment]
best way to workaround currently

dependency_overrides:
  provider:  ^6.0.0

**Comment by iamwasimaftab** [comment]
same error i also face. if anyone find any solution please share. @mirrorlink @mcagrigoktas @VNAPNIC 

Running "flutter pub get" in 33...                              
Because no versions of chewie match >1.2.2 <2.0.0 and chewie 1.2.2 depends on provider ^5.0.0, chewie ^1.2.2 requires provider ^5.0.0.
And because flutter_math_fork >=0.4.0 depends on provider ^6.0.0, chewie ^1.2.2 is incompatible with flutter_math_fork >=0.4.0.
So, because flutter_app_tv depends on both chewie ^1.2.2 and flutter_math_fork ^0.4.0, version solving failed.
pub get failed (1; So, because flutter_app_tv depends on both chewie ^1.2.2 and flutter_math_fork ^0.4.0, version solving failed.)
Process finished with exit code 1

**Comment by mirrorlink** [comment]
> same error i also face. if anyone find any solution please share. @mirrorlink @mcagrigoktas @VNAPNIC
> 
> Running "flutter pub get" in 33... Because no versions of chewie match >1.2.2 <2.0.0 and chewie 1.2.2 depends on provider ^5.0.0, chewie ^1.2.2 requires provider ^5.0.0. And because flutter_math_fork >=0.4.0 depends on provider ^6.0.0, chewie ^1.2.2 is incompatible with flutter_math_fork >=0.4.0. So, because flutter_app_tv depends on both chewie ^1.2.2 and flutter_math_fork ^0.4.0, version solving failed. pub get failed (1; So, because flutter_app_tv depends on both chewie ^1.2.2 and flutter_math_fork ^0.4.0, version solving failed.) Process finished with exit code 1

just add

dependency_overrides:
provider: ^6.0.0

to yaml

**Comment by mirrorlink** [comment]
in fact I think 1.2.3 is in place now

**Comment by imtoori** [comment]
+1

**Comment by Sarubbaru** [comment]
+1

**Comment by NazarenoCavazzon** [comment]
+1

**Comment by S-ecki** [comment]
+1

**Comment by diegotori** [comment]
Version 1.3.0 is now live on pub.dev, which upgrades Provider to ^6.0.1 as well as wakelock to the latest version.
