### ISSUE TITLE
Getting error when playing AWS cloudfront URL in Flutter web

### ISSUE THREAD

**Issue by rahulvyas** [fluttercommunity/chewie#656]
Error: PlatformException(MEDIA_ERR_SRC_NOT_SUPPORTED, No further diagnostic information can be determined or provided., The video has been found to be unsuitable (missing or in a format not supported by your browser)., null)

**Comment by shehangamage** [comment]
same here

**Comment by diegotori** [comment]
@rahulvyas based on the fact that it's a `PlatformException`, this error is definitely coming from `video_player`, since `chewie` is merely a UI wrapper around that library.

Please bring up this issue with a reproducible example to the Flutter GitHub repo, since that's where you can raise issues related to first party plugins.

**Comment by rahulvyas** [comment]
@diegotori Thanks for the heads up. I'll add the same issue in the official repo.
